# Train Test Frameworks
These are simple exercises for practicing syntax of various functions from sklearn that split data into the train and test sets. The goal is to get familiar with these methods prior to the more complex challenge at the end of the day.

In [1]:
# import numpy
import numpy as np

In [2]:
X = np.random.normal(0,1,20).reshape(10,2)
y = np.random.normal(0,1,10)

* print X

In [3]:
print(X)

[[ 2.42487647 -0.18167835]
 [ 1.18342811  2.17541812]
 [ 1.14399131  0.34035822]
 [ 0.62576093 -1.28861051]
 [-0.08666764 -0.97462146]
 [ 1.7109252  -0.1333782 ]
 [-0.14709733 -0.99918156]
 [ 0.42266381  0.53552063]
 [ 0.177116   -1.85743022]
 [ 0.97337452 -2.14143857]]


* print y

In [4]:
print(y)

[-0.20195582  0.27355625 -2.49392416  0.63090553 -1.02362042  0.04027911
  0.18278155  0.36557399  0.4078307   2.33020669]


## HOLDOUT split

* import train_test_split function from sklearn

In [6]:
from sklearn.model_selection import train_test_split

* split the data to train set (70%) and test set (30%)

In [7]:
X_train, X_test, y_train,y_test = train_test_split(X,y,train_size=0.7,test_size=0.3,random_state=101)

* print X_train

In [8]:
print(X_train)

[[-0.08666764 -0.97462146]
 [ 0.97337452 -2.14143857]
 [ 0.62576093 -1.28861051]
 [ 1.7109252  -0.1333782 ]
 [ 0.42266381  0.53552063]
 [-0.14709733 -0.99918156]
 [ 1.18342811  2.17541812]]


* split the data again but now with  shuttle=False

In [9]:
X_train, X_test, y_train,y_test = train_test_split(X,y,train_size=0.75,test_size=0.25,random_state=101, shuffle=False)

* print X_train

In [10]:
print(X_train)

[[ 2.42487647 -0.18167835]
 [ 1.18342811  2.17541812]
 [ 1.14399131  0.34035822]
 [ 0.62576093 -1.28861051]
 [-0.08666764 -0.97462146]
 [ 1.7109252  -0.1333782 ]
 [-0.14709733 -0.99918156]]


* print shape of X_train and X_test

In [11]:
print(X_train.shape)
print(X_test.shape)

(7, 2)
(3, 2)


## K-FOLD split 

* import KFold from sklearn

In [12]:
from sklearn.model_selection import KFold

* instantiate KFold with k=5

In [13]:
kf = KFold(n_splits=5)

* iterate over train_index and test_index in kf.split(X) and print them

In [26]:
for train_index,test_index in kf.split(X):
    X_train,X_test = X[train_index],X[test_index]
    y_train,y_test = y[train_index],y[test_index]
print(X_train,X_test)

[[ 2.42487647 -0.18167835]
 [ 1.18342811  2.17541812]
 [ 1.14399131  0.34035822]
 [-0.08666764 -0.97462146]
 [ 1.7109252  -0.1333782 ]
 [ 0.42266381  0.53552063]
 [ 0.177116   -1.85743022]
 [ 0.97337452 -2.14143857]] [[ 0.62576093 -1.28861051]
 [-0.14709733 -0.99918156]]


* instantiate KFold with k=5 and shuffle=True

In [17]:
kf = KFold(n_splits=5, shuffle = True)

* iterate over train_index and test_index in kf.split(X) and print them

In [18]:
for train_index,test_index in kf.split(X):
    X_train,X_test = X[train_index],X[test_index]
    y_train,y_test = y[train_index],y[test_index]
print(X_train, X_test)

[[ 2.42487647 -0.18167835]
 [ 1.18342811  2.17541812]
 [ 1.14399131  0.34035822]
 [-0.08666764 -0.97462146]
 [ 1.7109252  -0.1333782 ]
 [ 0.42266381  0.53552063]
 [ 0.177116   -1.85743022]
 [ 0.97337452 -2.14143857]] [[ 0.62576093 -1.28861051]
 [-0.14709733 -0.99918156]]


## LEAVE-ONE-OUT split
this is a similar technique like the Leave-p-out in the previous readings, with p=1. Each observation is used as test set separately.
- it's popular method for very small datasets
- takes a lot of time for bigger data and can lead to overfitting of a final model.

* import LeaveOneOut from sklearn

In [19]:
from sklearn.model_selection import LeaveOneOut

* instantiate LeaveOneOut

In [20]:
loo = LeaveOneOut()

* iterate over train_index and test_index in loo.split(X) and print them

In [22]:
for train_index, test_index in loo.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train)
    print(X_test)

[[ 1.18342811  2.17541812]
 [ 1.14399131  0.34035822]
 [ 0.62576093 -1.28861051]
 [-0.08666764 -0.97462146]
 [ 1.7109252  -0.1333782 ]
 [-0.14709733 -0.99918156]
 [ 0.42266381  0.53552063]
 [ 0.177116   -1.85743022]
 [ 0.97337452 -2.14143857]]
[[ 2.42487647 -0.18167835]]
[[ 2.42487647 -0.18167835]
 [ 1.14399131  0.34035822]
 [ 0.62576093 -1.28861051]
 [-0.08666764 -0.97462146]
 [ 1.7109252  -0.1333782 ]
 [-0.14709733 -0.99918156]
 [ 0.42266381  0.53552063]
 [ 0.177116   -1.85743022]
 [ 0.97337452 -2.14143857]]
[[1.18342811 2.17541812]]
[[ 2.42487647 -0.18167835]
 [ 1.18342811  2.17541812]
 [ 0.62576093 -1.28861051]
 [-0.08666764 -0.97462146]
 [ 1.7109252  -0.1333782 ]
 [-0.14709733 -0.99918156]
 [ 0.42266381  0.53552063]
 [ 0.177116   -1.85743022]
 [ 0.97337452 -2.14143857]]
[[1.14399131 0.34035822]]
[[ 2.42487647 -0.18167835]
 [ 1.18342811  2.17541812]
 [ 1.14399131  0.34035822]
 [-0.08666764 -0.97462146]
 [ 1.7109252  -0.1333782 ]
 [-0.14709733 -0.99918156]
 [ 0.42266381  0.53552063]

* print the number of splits

In [24]:
print(loo.get_n_splits(X))

10
